### ISSUE TITLE
Atomizer_ReadInfo() issue

### ISSUE THREAD

**Issue by ploop** [ReservedField/evic-sdk#14]
When call `Atomizer_ReadInfo()` and state is power off, for measurement converter started with 1V output. I think it's a lot. If resistance is 0.1 ohm is already 10A current and 10W power. Thin Ni coil heats up if check resistance  2-3 times in second, and it high energy consumption. 

Maybe add 2-3 level, start at 0.3-0.5V, if resistance is large - set 1V or more?

**Comment by ReservedField** [comment]
Well, you're not supposed to do that 2-3 times a second:

```
/**
 * Reads the atomizer info.
 * If the atomizer is powered off, this powers it on for a
 * few milliseconds at a very low voltage, in order to
 * measure its parameters. Because of this, avoid continually
 * calling it while not firing.
 *
 * @param info Info structure to fill.
 */
void Atomizer_ReadInfo(Atomizer_Info_t *info);
```

What are you doing that requires such frequent checks while not firing?

Apart from that, you're right: the original firmware uses multiple levels. If I got it right it's 1V the first time around, then 5/10/15W depending on the case, but I need to check it further and improve the algorithm. So OFW does fire it at 1V. But it doesn't call it nearly as often as 2-3 times per second.
I will also try to figure how much we can decrease power without losing accuracy, but I don't think there's much room there.

**Comment by ploop** [comment]
> What are you doing that requires such frequent checks while not firing?

For example, update information on display at realtime (resistance). 

> original firmware uses multiple levels

I do not see it. In oscillograms 0.5V ~5Hz  http://i.imgur.com/o4tl3TT.png Maybe when set atomizer first pulses is different, need check it.

**Comment by ReservedField** [comment]
I see that OFW actually checks 5 times a second. Didn't know, thanks for the scope pics (by the way, do you happen to have traces for the atomizer firing? I'm curious as to how fast it converges to the target voltage).

So, that part of OFW code is a mess (bunch of gotos, unknown vars, etc), but it goes something like this: there's a 0-10 counter and based on it different volts/watts are chosen:

```
0-7 --> 1.00V
  8 --> 5.0W (if voltage comes out non-zero, otherwise 1.00V)
  9 --> 10.0W
 10 --> 15.0W
```

(note that resistance must be already known for calculating volts from watts, so first reading is always 1V). I have to investigate more on how this counter is increased (and stopped, it seems).
What resistance is your coil? For the lowest power (5W) 0.5V means a 0.05ohm coil.

(by the way, for you folks at ecigtalk: GLCD Font Creator and LCD Image Converter won't generate correct bitmaps for the SDK, you need The Dot Factory. More info about SDK fonts in issue #2)

**Comment by ploop** [comment]
> I'm curious as to how fast it converges to the target voltage

http://img.mysku-st.ru/uploads/images/02/62/17/2015/10/17/6b2c4f1fd1.png
Where voltage down, I put coil into the water.
To see a more rapid response, we need bread board  and disassemble evic. I did it when coming new mod, just evic is one I have.

> What resistance is your coil?

On scope picture? I don't remember. I did it two months ago.

> by the way, for you folks at ecigtalk: GLCD Font Creator and LCD Image Converter won't generate correct bitmaps for the SDK, you need The Dot Factory

You are reading ecigtalk? о_О 
I can try to implement it in the LCD Image Converter, if I have time. Although there are a lot of settings, maybe have custom format.

**Comment by ReservedField** [comment]
> To see a more rapid response, we need bread board and disassemble evic.

Why? Measuring at the 510 connector should be accurate enough. It's what the atomizer sees. Faster convergenge can be obtained by changing the +/- 1 increment in the feedback loop, at the price of less output stability. Maybe it could be better to change the 5kHz feedback frequency, but we'd have to calculate whether the ADC can keep up (it's 1MS/s so I guess it can). Unless you mean modding the hardware to get faster rise?

> You are reading ecigtalk? о_О 
> I can try to implement it in the LCD Image Converter, if I have time. Although there are a lot of settings, maybe have custom format.

It showed up as a traffic source in Github stats, so I checked it out. By alternating between English and Italian translations I can get some meaning out of it :P
Framebuffer/bitmap format is documented in Display.h. I hope you don't hit any bugs, or you're gonna pull your hair out when you see Display_BitCopy (yes, it was necessary).

So, datasheet gives 2560mV +/- 77mV for the reference and +/- 4LSB for the ADC. Assuming worst case (2637mV reference, 1.05mOhm shunt) I get +/- 11.16mV for atomizer voltage and +/- 24.5mA for current shunt. Pretty precise, I'd say. Relative error on resistance is the sum of relative errors on voltage and current. I plugged everything into Mathematica and got [this table](http://i.imgur.com/SIecVvT.png) (dR is absolute error on resistance, dR/R is relative error). For bigger resistances, using low voltages results in awful precision, so I'll have to implement something smart...

**Comment by ploop** [comment]
> Unless you mean modding the hardware to get faster rise?

No, hardware must be unaltered. 
For measure response need fast change resistance. Need take a two coils, first coil connect directly, second coil connect via mechanical switch, and thereto two channel scope. During fiering switch set on (or off, if need resistance rise), and look. 

>  I hope you don't hit any bugs, or you're gonna pull your hair out when you see Display_BitCopy

That works, and good works! :)

> For bigger resistances, using low voltages results in awful precision, so I'll have to implement something smart...

Like this? 

``` c
if(Atomizer_curState == POWEROFF) {
   // Power on at 1.00V for measurement
   savedTargetVolts = Atomizer_targetVolts;
   uint16_t testVolts;
   testVolts = 200;
   while (ATOMIZER_ADC_RESISTANCE(vSum, iSum) > XXX && testVolts < YYY )
   {
      Atomizer_SetOutputVoltage(testVolts);
      Atomizer_Control(1);
       .....
       testVolts += 200; // 
     }
```

**Comment by ReservedField** [comment]
I did some measurements. Looks like the OFW isn't actually measuring it all the time. I see 300mV pulses: those are just to check if the atomizer is still there, and to check it's not shorting/open. That's why it didn't make sense.

**Comment by ploop** [comment]
>  just to check if the atomizer is still there, and to check it's not shorting/open

I think so. We must do better :)

**Comment by ReservedField** [comment]
We can go two ways about it:
- Start from low voltage, monitor current. Calculate error on resistance from current (easy). If error is too big, increase voltage, and try again. Repeat until target error is achieved. This takes a few iterations, so it's a bit slow. Note that we can't rely on the resistance value like you did in your code: at low voltage, a big resistance can be waaaay off (i.e. 3.5ohms @ 0.2V has -36%/+105% error). Current and voltage have fixed absolute errors, so it's easier to use them for calculations.
- Use 1V to get an initial resistance estimate (max 10% error). Then, feed it to a linear function I found to calculate the optimal voltage to get a target precision. Measure resistance using this voltage. Using an approximate resistance as an input of course does not give the precise voltage, but since the function has a positive slope and the error tends to over-estimate the resistance we actually get more than we asked for. In case, more iterations can be added to further refine it, but it shouldn't be necessary.

Original firmware does 11 iterations. The seconds method does 2. The first one does a lot more for big resistances if the step is fixed (but a non-liear step could solve that).

Either way, we can't keep doing it continuosly - it WILL heat up the atomizer. Method 2 has an average power of nearly 9W over the whole resistance range (including the 1V test, and skipping the second test if the optimal voltage is < 1V). So average heat per measurement is 18mJ. Method 1 is surely much above 16mJ. Doing method one 5 times a second is an average power of 90mW, not bad. Problem is: look at the worst case... that is, 0.05ohm (lowest resistance, even though the conditional makes it not so trivial). There you have 20W of testing power. Doing it frequently will heat it up, just like you saw.

Is there a reason why it's not ok to measure the resistance the first time and then just check if it's disconnected or shorted? It seems to me that it shouldn't change if not firing. Am I missing something?

**Comment by ReservedField** [comment]
I added some new support in the `experimental` branch (commit d66b66d). Not 100% stable yet.

**Comment by zygisber** [comment]
Not good. “NO ATOM” if atomizer is off. Your example does not even fire for me, display switches from “NO ATOM” to “SHORT” while fire button is down without actually powering atomizer. And Atomizer_ReadInfo allways returns zeros if atomizer is off.

**Comment by ReservedField** [comment]
I'm working on it. Let's just say that, as far as atomizer and coil control goes, there's far more than meets the eye.
By the way, next commit (hoping tomorrow) will also have a better slew rate. Yay :)

**Comment by ReservedField** [comment]
A lot of improvements are in commit 8a9144b. Available in the `experimental` branch. Could you guys test it and report back?

**Comment by zygisber** [comment]
On it!

**Comment by ploop** [comment]
With pleasure. Tomorrow :)

**Comment by ploop** [comment]
I think, we should allow user to determine the test pulse (in include/atomizer.h) if state== POWEROFF
`void Atomizer_ReadInfo(Atomizer_Info_t *info, uint16_t volts, uint16_t time);`

**Comment by ReservedField** [comment]
@ploop I'm not sure I'm following you. You mean allow the user to decide the test voltage for res measuring? Why? Do you mean the 300mV presence pulse?
(about res measure, it's not a simple pulse - it's a refinement of test voltages for progressively more precise resistances, until the res stabilizes)

**Comment by ploop** [comment]
I mean SDK-user, i.e. firmware programmer :)

**Comment by ReservedField** [comment]
Yes, I got that. I mean, what should be exposed? The voltage for res measuring, the presence voltage...?
But most importantly, why?

**Comment by ploop** [comment]
For custom atomizer control algoritm on not fire state. As an addition to the main.
Or can use for this purpose Atomizer_Control()?

**Comment by ReservedField** [comment]
Well, comment out Atomizer_Init from startup and do it yourself? :P
Seriously though, there are two test voltages at play. One is the detection voltage, used when no atomizer is detected to check if a new atomizer has been plugged in. It's 300mV and runs every 200ms (just like OFW). The other is the voltage used for actual resistance measurement, and it's not fixed (starts at 1.00, then gets refined to lower/higher values until the readings converge to a sufficient precision).
The first one _could_ easily be made configurable, but I don't see any use for it. If you up it, you get heating. If you lower it, too much error starts creeping in for short/open detection.
The second one is not easily configurable, since it is dinamically adjusted to the resistance before the resistance is even known to the user.

I'm still working on the atomizer algorithms, they're far from 100% stable. Maybe you could propose the custom algorithm you intend to use and if works well we can implement it in the SDK? I'd be happy to help you get what you want, but I'm going to need a bit more info.

(btw, just pushed some changes in the experimental branch to correct a bug that has been reported to me)

**Comment by ploop** [comment]
> The other is the voltage used for actual resistance measurement, and it's not fixed (starts at 1.00, then gets refined to lower/higher values until the readings converge to a sufficient precision).

It is already working in the experimental branch? I build it, but not testing properly. This is what I wanted!

**Comment by ReservedField** [comment]
Well, that was the whole point about that branch.

> I build it, but not testing properly.

Is it not working or you didn't test it yet? If you didn't, you should :)

Every 200ms the atomizer is checked. If a new atomizer is detected, a 1.00V test voltage is applied for 2ms and resistance is measured. From this resistance, a new test voltage is calculated (with a formula I wrote) and stored. At the next 200ms mark, the new test voltage is used, resistance is measured, and a new test voltage is calculated. This continues until the resistance differs by at most 5mOhm from last reading (be sure to update with the latest commit!). At this point, resistance is stored and not measured anymore. Just checked every 200ms for atomizer disconnection.

**Comment by ploop** [comment]
> Is it not working or you didn't test it yet? If you didn't, you should :)

I didn't test it for bug, upload a few minutes ago - working!

**Comment by ReservedField** [comment]
I have no idea why I never closed this.
